### ISSUE TITLE
Add support for GD

### ISSUE THREAD

**Issue by aran112000** [brefphp/extra-php-extensions#10]
We require the GD library (bref/php-74-fpm) for processing WebP images, any chance this is an easy one to add?

**Comment by mnapoli** [comment]
Hi, GD was added in https://github.com/brefphp/bref/pull/396 but it seems that [this page](https://bref.sh/docs/environment/php.html) was not updated to reflect it. If you can send a pull request to update it that would be awesome.

**Comment by aran112000** [comment]
Amazing, thanks @mnapoli, I'll give it a try now and if all working, I'll open a PR this evening :)

**Comment by aran112000** [comment]
Hi @mnapoli,

I've managed to deploy with GD, however, it appears to be a minimal install and is missing the main function we actually need from it:
https://www.php.net/manual/en/function.imagewebp.php

Do you think it'd be easy to recompile to include this, not sure how that works exactly, sorry.

Thanks in advance - Aran

**Comment by mnapoli** [comment]
Thanks for the PR!

I wouldn't call it that minimal as we included PNG and JPG support. But I don't recall adding webp indeed. The challenge to add that is to identify which system libraries to install and package in the layer.

**Comment by aran112000** [comment]
Hi @mnapoli,

I've done some looking into it this evening, and it sounds as though it's just libwebp that's required - here's a quick extract from PHP's docs on it, hope this helps a quick resolution 🤞:

> As of PHP 7.0.0 --with-webp-dir=DIR has to be added, i.e. support for libvpx has been removed in favor of libwebp.
https://www.php.net/manual/en/image.installation.php

**Comment by mnapoli** [comment]
👍 Here is an outline of the process to get this into Bref (in the main repository), like for other extensions:

- open a pull request that adds the flag, as well (probably required) as the system library
- confirm that the extension works
- show the difference of size of the layers (before/after) so that we can check that it's not adding too much

**Comment by aran112000** [comment]
Hi @mnapoli,

I've achieved the first 2 parts, although feel completely lost when trying to create the layers themselves, any chance you could point me in the right direction?

Cheers,
Aran

**Comment by mnapoli** [comment]
Sure! When you build the layers with Bref, you have to do: 

```
cd runtime
make runtimes
```

The generated layers will be in the `runtime/export/` directory.

What you can do is `ls -la` and paste the result in the pull request (that you can create over the Bref repository).

That way we can see the new size of the layers. We can then compare that with the current layers (I will do that, I have them already built on my machine).

**Comment by mnapoli** [comment]
(btw just to be clear: the layers are ZIP files).

**Comment by Nyholm** [comment]
What is the status here? Should we add "minimal-GD" and "full-GD" in this repo?

Or should we close or move this issue to brefphp/bref?

**Comment by mnapoli** [comment]
Hi! We can close here, there is https://github.com/brefphp/bref/pull/531

What https://github.com/brefphp/bref/pull/531 is missing is a preview of how bigger the new layers become. I haven't had time to build them myself yet.

If it turns out that the layers become too big for Bref, we can reopen this issue.
