### ISSUE TITLE
gmp: Unable to initialize module

### ISSUE THREAD

**Issue by hvipana** [brefphp/extra-php-extensions#109]
Hi, gmp is not working anymore.

```
PHP Warning:  PHP Startup: gmp: Unable to initialize module
Module compiled with build ID=API20190902,TS
PHP    compiled with build ID=API20190902,NTS
These options need to match
```

composer.json:
```
"bref/bref": "^1.0",
"bref/extra-php-extensions": "^0.6.3",
```

Runtime: `provided.al2`

**Comment by Nyholm** [comment]
All the issues should be solved in 0.6.4 (will be released today)

**Comment by hvipana** [comment]
Thank you, gmp is working now.

**Comment by Nyholm** [comment]
Cool. I got a bit worried for a moment. 0.7.0 will include some tests so this will not be repeated.
