### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by RTC1** [brefphp/extra-php-extensions#110]
Hello,

I'm trying to use the MongoDB extension in my local docker environment. So far i've got the following:

Dockerfile
```
FROM bref/extra-mongodb-php-74 as mongodbextra
FROM bref/php-74-fpm-dev
COPY --from=mongodbextra /opt/bref-extra/mongodb.so /opt/bref-extra/
```

php/conf.d/mongo.ini
```
extension=/opt/bref-extra/mongodb.so
```

I'm getting this:

`PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/bref-extra/mongodb.so' (tried: /opt/bref-extra/mongodb.so (/opt/bref-extra/mongodb.so: undefined symbol: executor_globals)`

I haven't been able to locate a guide as to how to use these docker images. Can someone please advise?

**Comment by RTC1** [comment]
Possibly related to #109 & #104

**Comment by Nyholm** [comment]
Yeah.. I think so too... I'll try to fix it as soon as I get home from work

**Comment by Nyholm** [comment]
Hey!

I think you are all correct. We actually doing the exact same thing now when testing the Docker images. Does it work for you now?

**Comment by RTC1** [comment]
Unfortunately not - I've cleared out all my docker cached images too. 
```
bash-4.2$ php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/bref-extra/mongodb.so' (tried: /opt/bref-extra/mongodb.so (/opt/bref-extra/mongodb.so: undefined symbol: executor_globals), /opt/bref/lib/php/extensions/no-debug-zts-20190902//opt/bref-extra/mongodb.so.so (/opt/bref/lib/php/extensions/no-debug-zts-20190902//opt/bref-extra/mongodb.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 7.4.10 (cli) (built: Sep 25 2020 14:01:27) ( ZTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.10, Copyright (c), by Zend Technologies
```

**Comment by Nyholm** [comment]
Hm.. 

Im not able to reproduce the bug in https://github.com/brefphp/extra-php-extensions/blob/master/layers/mongodb/test.php

When I run `layer=mongodb php_versions=74 make test` we basically test on an container created from image: 

```
FROM bref/extra-mongodb-php-74 as mongodbextra
FROM bref/php-74-fpm-dev
COPY --from=mongodbextra /opt /opt
```

(See `./test`). 

-------

Maybe that is what you are doing wrong..

```diff
 FROM bref/extra-mongodb-php-74 as mongodbextra
 FROM bref/php-74-fpm-dev
-COPY --from=mongodbextra /opt/bref-extra/mongodb.so /opt/bref-extra/
+COPY --from=mongodbextra /opt /opt
```

**Comment by RTC1** [comment]
I noticed when I ran it again it downloaded a new version of the image. All sorted thanks!

Definitely worth adding that script to the readme for those of us using docker for local development.

**Comment by Nyholm** [comment]
I agree. Could you please do that?
Maybe create a new small testing about “use extensions with docker”?
