### ISSUE TITLE
Support for pgsql

### ISSUE THREAD

**Issue by sabmeua** [brefphp/extra-php-extensions#12]
I really thank you for your great work.
I added support for pgsql (not pdo-pgsql) so I'd like to pull request it if it works fine.

https://github.com/sabmeua/extra-php-extensions/tree/ext_pgsql

Now I made sure that the build is good with Travis CI. But I don't know how to add it to my serverless.yml as new layer and confirm it.

https://travis-ci.org/sabmeua/extra-php-extensions

I guess that to add a new layer, it needs to create a zip file from the docker image which generated above. How to create the zip file?

**Comment by sabmeua** [comment]
After that I manually created attached zip file from docker image, and added a new layer with this zip file.
Then I confirmed to access a RDS postgresql from lambda function by "pg_*" functions.
Is this good for confirmation method?

[php73-pgsql-layer.zip](https://github.com/brefphp/extra-php-extensions/files/4101795/php73-pgsql-layer.zip)

**Comment by Nyholm** [comment]
I think you are pretty much covered.
Great work. Could you submit a PR?

**Comment by sabmeua** [comment]
Thanks for comment. I submitted PR just now.

**Comment by Nyholm** [comment]
Thank you. 

You've done an excellent job with this PR. Could you describe your process (add docs)?
If you make another PR that fixes #14, that would be great.

**Comment by sabmeua** [comment]
Sure. I'd love to describe my process.
I have not yet understood how to use a locally built image as bref plug-in, so I hope to understand it through the PR.

**Comment by Nyholm** [comment]
One need to publish it with “aws lambda publish-layer-version”. 

Thank you. 
I’m closing this as it was fixed in #13 

Let’s continue discussion in #14
