### ISSUE TITLE
SQL Server Library Issues

### ISSUE THREAD

**Issue by fotzlapen** [brefphp/extra-php-extensions#128]
Hi Team,

Got an issue with using the bref:extra.sqlsrv-php-74 layer with the bref:layer.php-74.  Seems consistent if I downgrade the layers all the way back to bref:layer.php-72.

So with these layers:

```
  layers:
    - ${bref:layer.php-74}
    - ${bref:extra.sqlsrv-php-74}
```

I consistently get the error:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/bref-extra/pdo_sqlsrv.so' (tried: /opt/bref-extra/pdo_sqlsrv.so (**/opt/bref-extra/pdo_sqlsrv.so: undefined symbol: executor_globals**), /opt/bref/lib/php/extensions/no-debug-zts-20190902//opt/bref-extra/pdo_sqlsrv.so.so (/opt/bref/lib/php/extensions/no-debug-zts-20190902//opt/bref-extra/pdo_sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  require(/opt/bref/vendor/autoload.php): failed to open stream: No such file or directory in /opt/bootstrap on line 14
```

The file /opt/bref-extra/pdo_sqlsrv.so exists in the layer.

My php.ini is:

```
# Enable required extensions here
extension=/opt/bref-extra/pdo_sqlsrv.so

```
And my serverless environment variable is set:

`    ODBCSYSINI: /opt/microsoft/conf/
`

If I was going to make a guess I'd say that its because the pdo_sqlsrv.so file in the bref extras layer is configured to be not thread safe (NTS) while the php executable in bref-74 layer is configured to be thread safe (TS).

Any hints you could provide would be amazing.  Am I just doing something wrong here?

Cheers,

Damon

**Comment by Nyholm** [comment]
Thank you. 

The hint is this: 
> undefined symbol: executor_globals**

I've not been able to test that layer since I dont want to automatically include both extensions. 

I tested this myself and got a little bit different error: 

> PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/bref-extra/pdo_sqlsrv.so' (tried: /opt/bref-extra/pdo_sqlsrv.so (libltdl.so.7: cannot open shared object file: No such file or directory), /opt/bref/lib/php/extensions/no-debug-non-zts-20180731//opt/bref-extra/pdo_sqlsrv.so.so (/opt/bref/lib/php/extensions/no-debug-non-zts-20180731//opt/bref-extra/pdo_sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

That helped me undertand the fix.

**Comment by Nyholm** [comment]
See https://github.com/brefphp/extra-php-extensions/pull/129
