### ISSUE TITLE
Could we enable both memcache and memcached extension in the same layer?

### ISSUE THREAD

**Issue by Nyholm** [brefphp/extra-php-extensions#133]
Will this be a problem? Should we rather split it to two layers?

**Comment by Nyholm** [comment]
@Nemo64 do you know about this?

**Comment by Nemo64** [comment]
Sorry, no idea.

**Comment by Nyholm** [comment]
That's okey. 
I had the feeling that you knew this. Maybe because you are a hard code DynamoDB user I automatically imagine that you know other complicated stuff =)

**Comment by chippyash** [comment]
I've a feeling you should run one or the other. Back in the day I seem to remember issues with running both together. Could have been php 5x. Now we have redis, I don't use memcache any more. Worth checking though.
