### ISSUE TITLE
Bug in imagick when rendering text on a page - cannot write text on image (freetype missing?)

### ISSUE THREAD

**Issue by victormacko** [brefphp/extra-php-extensions#155]
In trying to write text on an image using Imagick, the following error comes up when using the imagick layer;

php-fpm: DelegateLibrarySupportNotBuiltIn '/var/task/public/fonts/Arial.ttf' (Freetype) @ warning/annotate.c/RenderFreetype/1844.
CRITICAL - request()] Uncaught PHP Exception ImagickException: "Failed to query the font metrics" at /var/task/src/GeoJSON2Image.php line 484

The line of code is the following;
$canvas = new Imagick();
....
$draw = new ImagickDraw();
$label = 'my label';
...
$metrics = $canvas->queryFontMetrics($draw, $label);

It's basically to add annotations (text, explaining parts of an image).
Any help would be appreciated -- i'm a little stuck with what to do, and it looks like there's some vague mention of it elsewhere, with a reference to freetype not being included when compiling imagick (when imagick was used in other projects (outside of Bref))

**Comment by Nyholm** [comment]
Im not sure either. Can you reproduce the error on your local machine? 

Could you update [this file](https://github.com/brefphp/extra-php-extensions/blob/master/layers/imagick/test.php) with a script that show that it fails?

**Comment by victormacko** [comment]
Done :)

**Comment by Nyholm** [comment]
I found [this answer from stackoverflow](https://stackoverflow.com/questions/6864890/imagick-failed-to-query-the-font-metrics). It suggested that I should run `convert -list configure` and look at the "delegates" section. I saw that Freetype was missing. 

I installed `ImageMagick-devel` and forced freetype support when compiling the extension. See my commits to #156

**Comment by victormacko** [comment]
@Nyholm Oh awesome, thanks so much for getting this going -- was just starting to wonder how I could try and reproduce & fix it here! Your work is super appreciated, thank you so much!

**Comment by jhernandis** [comment]
I’m sorry to be bringing this up from five years ago, but I’ve come across the same error.

When using Bref 3.0.6 with the Imagick php82 layer, I get an error when trying to use the FreeType library.

`php: DelegateLibrarySupportNotBuiltIn '/tmp/gfonts/Z9XUDmZRWg6M1LvRYsH-yMOInrib9Q.ttf' (Freetype) @ warning/annotate.c/RenderFreetype/2119.`

You can see that the library is present, but it is not linked to Imagick.

```
{
    "libfreetype_files": [
        "/opt/lib/libfreetype.so.6"
    ],
    "imagick_version": "ImageMagick 7.1.2-15 Q16-HDRI x86_64 818ee6363:20260222 https://imagemagick.org",
    "gd_freetype": true,
    "gd_version": "bundled (2.1.0 compatible)",
    "opt_lib": [
        "/opt/lib/libMagickCore-7.Q16HDRI.so.10",
        "/opt/lib/libMagickWand-7.Q16HDRI.so.10",
        "/opt/lib/libX11.so.6",
        "/opt/lib/libXau.so.6",
        "/opt/lib/libXpm.so.4",
        "/opt/lib/libaom.so.3",
        "/opt/lib/libbrotlicommon.so.1",
        "/opt/lib/libbrotlidec.so.1",
        "/opt/lib/libcrypt.so.2",
        "/opt/lib/libde265.so.0",
        "/opt/lib/libexslt.so.0",
        "/opt/lib/libfreetype.so.6",
        "/opt/lib/libgomp.so.1",
        "/opt/lib/libgraphite2.so.3",
        "/opt/lib/libharfbuzz.so.0",
        "/opt/lib/libheif.so.1",
        "/opt/lib/libicudata.so.67",
        "/opt/lib/libicui18n.so.67",
        "/opt/lib/libicuio.so.67",
        "/opt/lib/libicuuc.so.67",
        "/opt/lib/libjpeg.so.62",
        "/opt/lib/liblber-2.4.so.2",
        "/opt/lib/liblcms2.so.2",
        "/opt/lib/libldap_r-2.4.so.2",
        "/opt/lib/libonig.so.5",
        "/opt/lib/libpng16.so.16",
        "/opt/lib/libpq.so.5",
        "/opt/lib/libsasl2.so.3",
        "/opt/lib/libsodium.so.26",
        "/opt/lib/libsqlite3.so",
        "/opt/lib/libwebp.so.7",
        "/opt/lib/libwebpdemux.so.2",
        "/opt/lib/libwebpmux.so.3",
        "/opt/lib/libxcb.so.1",
        "/opt/lib/libxslt.so.1",
        "/opt/lib/libzip.so.5"
    ],
    "ldd_magickcore": "\tlinux-vdso.so.1 (0x00007ffc15b48000)\n\tliblcms2.so.2 => /opt/lib/liblcms2.so.2 (0x00007ff530521000)\n\tlibjpeg.so.62 => /opt/lib/libjpeg.so.62 (0x00007ff530499000)\n\tlibpng16.so.16 => /opt/lib/libpng16.so.16 (0x00007ff53045d000)\n\tlibheif.so.1 => /opt/lib/libheif.so.1 (0x00007ff530326000)\n\tlibwebpmux.so.3 => /opt/lib/libwebpmux.so.3 (0x00007ff530317000)\n\tlibwebpdemux.so.2 => /opt/lib/libwebpdemux.so.2 (0x00007ff530310000)\n\tlibwebp.so.7 => /opt/lib/libwebp.so.7 (0x00007ff53027a000)\n\tliblzma.so.5 => /lib64/liblzma.so.5 (0x00007ff53024f000)\n\tlibxml2.so.2 => /lib64/libxml2.so.2 (0x00007ff5300d5000)\n\tlibz.so.1 => /lib64/libz.so.1 (0x00007ff5300bb000)\n\tlibzip.so.5 => /opt/lib/libzip.so.5 (0x00007ff53009b000)\n\tlibm.so.6 => /lib64/libm.so.6 (0x00007ff52ffc0000)\n\tlibgomp.so.1 => /opt/lib/libgomp.so.1 (0x00007ff52ff6a000)\n\tlibgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff52ff3c000)\n\tlibc.so.6 => /lib64/libc.so.6 (0x00007ff52fd33000)\n\tlibde265.so.0 => /opt/lib/libde265.so.0 (0x00007ff52fcb0000)\n\tlibaom.so.3 => /opt/lib/libaom.so.3 (0x00007ff52f585000)\n\tlibstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007ff52f321000)\n\t/lib64/ld-linux-x86-64.so.2 (0x00007ff53099b000)\n\tlibbz2.so.1 => /lib64/libbz2.so.1 (0x00007ff52f30d000)\n\tlibcrypto.so.3 => /lib64/libcrypto.so.3 (0x00007ff52eded000)\n"
}
```
