### ISSUE TITLE
Automatically enable extensions?

### ISSUE THREAD

**Issue by mnapoli** [brefphp/extra-php-extensions#16]
Would it make sense to automatically enable extensions when the layer is used?

That would simplify the installation steps: just import the layer and that's it.

How? PHP currently looks for `*.ini` files in 2 places:

https://github.com/brefphp/bref/blob/c3ca836239e2a9d5445235599b2e932de267ddb7/runtime/base/php-74.Dockerfile#L76

I *think* this works (I kinda remember some problems with this months ago, not sure), and I *think* it would be possible for the extra layers to include a `pgsql.ini` file (for example) in `/opt/bref/etc/php/conf.d` that would load the extension.

WDYT?

**Comment by shouze** [comment]
yes it's a good idea!

**Comment by mnapoli** [comment]
The only thing I'm not sure about is whether it will work (in theory it should, but I never tested adding a `.ini` file in that directory).

In any case I'm 👍

**Comment by adrianuf22** [comment]
It make sense to me!

And, it works!

I'm currently using this on my Docker images to install and enable extensions:

````
COPY --from=bref/extra-gmp-php-74 /opt/bref-extra/gmp.so /opt/bref-extra/gmp.so
RUN echo 'extension=/opt/bref-extra/gmp.so' > /opt/bref/etc/php/conf.d/gmp.ini
````
> The path `/opt/bref-extra/` is not important, before this, I was using the default extensions path and just putting `extension=gmp.so` at .ini file and still works.

I saw this on my PHP local installation, all extensions have a .ini file created separated at the default `conf.d` directory (In this case, all files was created automacally after install with `apt-get`).

When run `php -m`, all modules are loaded and `php --ini` shows the .ini file of all extensions.

**Comment by Nyholm** [comment]
Cool!
