### ISSUE TITLE
Extensions failling to load

### ISSUE THREAD

**Issue by finiteinfinity** [brefphp/extra-php-extensions#162]
While looking through CW logs I came across a number of issues where dynamic libraries fail to load or tries loading twice. This only seems to occur with the gmp and redis libraries.

Example of errors below
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'redis' (tried: /opt/bref/lib/php/extensions/no-debug-non-zts-20200930/redis (/opt/bref/lib/php/extensions/no-debug-non-zts-20200930/redis: cannot open shared object file: No such file or directory), /opt/bref/lib/php/extensions/no-debug-non-zts-20200930/redis.so (/opt/bref/lib/php/extensions/no-debug-non-zts-20200930/redis.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

and 

```
PHP message: PHP Warning:  Module "gmp" is already loaded in Unknown on line 0
```

I am currently using these layers in the following merge order:
- arn:aws:lambda:eu-west-2:209497400698:layer:php-80-fpm:6
- arn:aws:lambda:eu-west-2:403367587399:layer:gmp-php-80:8
- arn:aws:lambda:eu-west-2:403367587399:layer:redis-php-80:8
- arn:aws:lambda:eu-west-2:403367587399:layer:gd-php-80:8

and `php.ini`
```
extension=redis
extension=intl
extension=/opt/bref-extra/gmp.so
```

Interestingly when changing the gmp extension to `extension=gmp` it instead failed to load the library (with same error as redis)

**Comment by Nyholm** [comment]
What version are you using? 

For 0.9*+ you dont need to specify the `extension=/opt/bref-extra/gmp.so`. 

If you are using Bref ^1.0, then make sure you remove `extension=redis` too and add the redis layer in your serverless.yml file.

**Comment by finiteinfinity** [comment]
Hi @Nyholm,

Just to confirm you are saying that adding the layers is enough to enable the extensions without having `extension=xyz` in the ini file?

**Comment by Nyholm** [comment]
Correct. Since 0.7. 

See the updated readme.

**Comment by finiteinfinity** [comment]
Ok thanks, closing this issue due to misunderstanding

**Comment by Nyholm** [comment]
Let me know if you have any other trouble. 

I see that you are one of the cool ones and using PHP 8. =)
