### ISSUE TITLE
SQLSRV extension error with libmsodbcsql

### ISSUE THREAD

**Issue by chrishanline** [brefphp/extra-php-extensions#179]
Starting with release 0.9.6, getting an error with the SQLSRV layer when connecting with `sqlsrv_connect()`. Using Bref 1.2.0.

```
[{
	"SQLSTATE": "01000",
	"code": 0,
	"message": "[unixODBC][Driver Manager]Can't open lib '\/opt\/microsoft\/msodbcsql17\/lib64\/libmsodbcsql-17.6.so.1.1' : file not found"
}]
```

Downgrading to `bref/extra-php-extentions` 0.9.5 fixes it while still using Bref 1.2.0.

**Comment by Nyholm** [comment]
Thank you for this issue. 

Interesting. There is no changes to SQLSRV between 0.9.5 and 0.9.6. See https://github.com/brefphp/extra-php-extensions/compare/0.9.5...0.9.6. 

Will it work on bref/extra-php-extentions 0.10.0?

Could you try to modify this test file to reproduce the error? https://github.com/brefphp/extra-php-extensions/blob/master/layers/sqlsrv/test.php

**Comment by chrishanline** [comment]
I can confirm that 0.9.6 fails but 0.9.5 is fine. 0.10.0 also fails.

Here is a test file that attempts a connection. `sqlsrv_connect` is expected to return false since there is no SQL Server available to connect to, but checking for the low-level error returned about the missing library. When the test passes it does take 1 second for the `LoginTimeout` time to expire.

```
<?php

// This test is for sqlsrv.so
if (!function_exists($func = 'sqlsrv_connect')) {
	echo sprintf('FAIL: Function "%s" does not exist.', $func).PHP_EOL;
	exit(1);
}

// This test is for pdo_sqlsrv.so
if (!extension_loaded('pdo_sqlsrv')) {
	echo sprintf('FAIL: PDO sqlsrv extension not loaded').PHP_EOL;
	exit(1);
}

// This test attempts a connection, forcing MS odbc libraries to be loaded
if (!sqlsrv_connect('localhost', ['LoginTimeout' => 1])) {
	foreach (sqlsrv_errors() as $error) {
		if ($error['SQLSTATE'] == '01000') {
			echo sprintf('FAIL: sqlsrv extension library not loaded. %s', $error['message']).PHP_EOL;
			exit(1);
		}
	}
}

exit(0);
```

**Comment by Nyholm** [comment]
Thank you. Im confused because I dont see any changes in that layer. Also, Im trying to run the code you provided but it passes.

See #180

**Comment by chrishanline** [comment]
Is it possible to pass an env variable to the test? The SQLSRV layer requires `ODBCSYSINI=/opt/microsoft/conf/` to be present for the MS ODBC driver to be found.

I'm betting an error `$error['SQLSTATE'] == '-49'` is being returned since `ODBCSYSINI` isn't present providing the correct path to find in the layer.

**Comment by Nyholm** [comment]
Sure, just using `putenv('ODBCSYSINI=/opt/microsoft/conf/');`.

**Comment by Nyholm** [comment]
I still fail to reproduce the issue. Could you try with the code in #180?

**Comment by Nyholm** [comment]
Maybe @atbreuer11 could help out?

**Comment by atbreuer11** [comment]
@chrishanline I was able to reproduce the issue and opened #181 to address this. Let me know if it works for you.
