### ISSUE TITLE
Generating images of PDFs with Imagick

### ISSUE THREAD

**Issue by joedixon** [brefphp/extra-php-extensions#184]
Hi,

I am using the Imagick layer with Laravel Vapor and need to be able to generate images of each page of a PDF. My code looks like this:

```php
$this->imagick->setResolution($this->resolution, $this->resolution);
$this->imagick->readImage("{$this->path}[{$index}]");
$this->imagick->setFormat($this->format);
```

I have confirmed file exists in the `/tmp` directory, but when the `readImage` method is executed, I get the following exception:

```
ImagickException: Failed to read the file
```

I have also tried reading the file in with `readImageBlob` like so:

```php
$this->imagick->setResolution($this->resolution, $this->resolution);
$this->imagick->readImageBlob(file_get_contents($this->path));
$this->imagick->setIterator($index);
$this->imagick->setFormat($this->format);
```

This results in the following exception:

```
ImagickException: Unable to read image blob
```

Does anybody now how this can be resolved?

**Comment by mnapoli** [comment]
Hi! TBH I think the error message is not sufficient to know for sure.

Could it be that the image is corrupted/invalid? Where is the image coming from?

Also just a bit of warning: we do not know how the Vapor runtime is set up. They recommend using Bref layers with Vapor, so I guess they have tested it. But it's hard for us to say for sure that everything should work correctly, hopefully that makes sense.

**Comment by joedixon** [comment]
Hey @mnapoli - thanks for the quick response. That all makes perfect sense. Unfortunately, that's the extent of the error imagick supplies!

The image comes from S3, but I have tried pulling it in to the `/tmp` directory and allowing imagick to read it from there or passing it directly with `file_get_contents`. Both return similar errors, but I can see the image is being passed correctly and is not corrupted.

I'll keep digging around and let you know if I find the answer.

In the meantime, if anyone has any other suggestions, please let me know.

Thanks.

**Comment by Nyholm** [comment]
If you find an issue, it would be great if you modified this file to show the error: 

https://github.com/brefphp/extra-php-extensions/blob/master/layers/imagick/test.php

**Comment by Nyholm** [comment]
This should be fixed in 0.10.2. Could you please confirm?

**Comment by Nyholm** [comment]
@joedixon Did 0.10.2 fix the issue?

**Comment by Nyholm** [comment]
Im closing this due inactivity.
