### ISSUE TITLE
Add to packagist

### ISSUE THREAD

**Issue by Nyholm** [brefphp/extra-php-extensions#2]
We should review/change the package name in composer.json and then add this package to packagist. 

(If package name is changed in composer.json we also need to update the readme (plugin path))

**Comment by mnapoli** [comment]
The `bref/extra-php-extensions` Composer package looks good to me, should I add it to packagist?

**Comment by Nyholm** [comment]
Yes please.

**Comment by mnapoli** [comment]
👍  done: https://packagist.org/packages/bref/extra-php-extensions
