### ISSUE TITLE
Unknown Bref variable

### ISSUE THREAD

**Issue by RTC1** [brefphp/extra-php-extensions#218]
Just updated to serverless 2.38.0 from 2.35.0 and getting this:

`Cannot resolve variable at "functions.customSMSSender.layers.1": Error: Unknown Bref variable ${bref:extra.mongodb-php-80}, the only supported syntax right now is ${bref:layer.XXX}`

customSMSSender:
    handler: lambda_functions/LaravelHandle.php
    timeout: 180
    layers:
      - ${bref:layer.php-80}
      - ${bref:extra.mongodb-php-80}

Is there a new syntax that must be used?

**Comment by mnapoli** [comment]
I've opened https://github.com/brefphp/extra-php-extensions/pull/219, thank you for the report.

**Comment by mnapoli** [comment]
@RTC1  can you test https://github.com/brefphp/extra-php-extensions/pull/219 and confirm whether it solves the problem?

**Comment by johangit** [comment]
I'm trying to use the new variables:
```
- ${bref-extra:gd-php-74}
```

and got this Serverless error: "Invalid variable reference syntax for variable bref-extra:gd-php-74. You can only reference env vars, options, & files. You can check our docs for more info."

What I'm doing wrong? (`${bref:extra.gd-php-74}` works for me)


-----
```
> serverless -v
Framework Core: 2.52.1 (standalone)
Plugin: 5.4.3
SDK: 4.2.5
Components: 3.14.0
```

```
bref/bref                          1.2.8
bref/extra-php-extensions          0.10.10
```

**Comment by mnapoli** [comment]
I would suggest to upgrade to v0.11 of `bref/extra-php-extensions`
