### ISSUE TITLE
Layer ARN

### ISSUE THREAD

**Issue by deleugpn** [brefphp/extra-php-extensions#23]
I'm looking into integrating AWS Cognito and we're making use of [JWT Framework](https://web-token.spomky-labs.com/) to validate the tokens. I'll be needing the GMP extension, but I don't use the Serverless Framework. I wanted to know what's the Layer ARN that I can use to enable the extension.

Thanks!

**Comment by mnapoli** [comment]
Sorry it's pretty bare but here is the layer ARN: https://github.com/brefphp/extra-php-extensions/blob/master/index.js#L30 

And versions are here: https://github.com/brefphp/extra-php-extensions/blob/master/layers.json

**Comment by deleugpn** [comment]
This is more than enough! Thank you!!
