### ISSUE TITLE
New Relic Extension doesn't work with infrequent requests

### ISSUE THREAD

**Issue by NeilJ247** [brefphp/extra-php-extensions#252]
Hi,

I currently have a lambda application that is run about once a day.  The app is configured to report to daemon running in AWS Fargate.  The agent however is not logging web transactions or exceptions on a single request.  

I have spoken to @goldenplec about this around March (sorry Aidan I got busy...) who implemented this extension.  It is something to do how the agent collates the data and then sends to the daemon.  @goldenplec will explain it a lot better than I ever could.  

We did try a few things but nothing worked.  So raising this here to see what can be done and to make people aware of the limitations of this extension.

**Comment by Cerwym** [comment]
I also have this issue

**Comment by NeilJ247** [comment]
Hi @goldenplec, I think we tried this (sorry my memory is just as bad!).  I'll give it a go again.

**Comment by NeilJ247** [comment]
Hi @goldenplec,

Managed to get this working by setting `newrelic.daemon.app_timeout` to 120H and `newrelic.daemon.app_connect_timeout` to 15s in `newrelic-settings.ini`.

Thanks for your help.

**Comment by goldenplec** [comment]
@NeilJ247 awesome news. Sorry you were in limbo all this time. I thought this had been resolved your side when I hadn't heard back. Delighted it's all working for you.
