### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by alexanderkraemer** [brefphp/extra-php-extensions#306]
Anything else I need to do in order to get Memcached/Redis Extension to work besides adding the two layers to my function?
I've added the following two 
`${bref-extra:memcached-php-74}`
`${bref-extra:redis-php-74}`

I'm still getting errors such as:
```
Error: Class "Redis" not found in file /var/task/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php on line 75
```

PHP: 8.0
Bref version: 1.4.1
Bref extra-php-extensions version: 0.11.21

**Comment by davidsickmiller** [comment]
How did you fix this?
