### ISSUE TITLE
Newrelic extension

### ISSUE THREAD

**Issue by tlfbrito** [brefphp/extra-php-extensions#34]
This isn't a bug, it a suggestion.

Create an extension layer with the Newrelic APM.

**Comment by mnapoli** [comment]
I think the New Relic APM would need an agent running all the time, right? If that's the case, you would need to run that daemon on an EC2 box I guess (like Blackfire).

**Comment by Nyholm** [comment]
Yes. That is correct. But NewRelic does not support the agent on a different server as far as I know.. Or can that be done?

**Comment by awons** [comment]
@Nyholm It can be done since agent 9.2: https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-920247

**Comment by Nyholm** [comment]
It will be added at the next release
