### ISSUE TITLE
Bref mcrypt extension layer, 

### ISSUE THREAD

**Issue by prakashhiranandani** [brefphp/extra-php-extensions#345]
Hi ,
  Thanks alot for creating the bref laravel library, I create a lambda function but it does not have mcrypt installed.
   Is there a bref layer which has mcrypt  installed

Thanks
Prakash

**Comment by Nyholm** [comment]
The mcrypt extension was removed in PHP 7.2

https://www.php.net/manual/en/intro.mcrypt.php
