### ISSUE TITLE
Bref 2.0

### ISSUE THREAD

**Issue by mnapoli** [brefphp/extra-php-extensions#375]
Hey @Nyholm!

As I work on Bref v2, I started testing the impact on the extra extensions. I think it _should_ be minimal.

So far I've been able to build redis, decimal, and ds by just replacing:

```diff
- FROM bref/build-php-$PHP_VERSION:1.7.4 AS ext
+ FROM --platform=linux/amd64 bref/build-php-$PHP_VERSION:latest AS ext
```

Note: I used `latest` so that it uses the local image I built from https://github.com/brefphp/aws-lambda-layers Eventually you'll be able to use a real version like 2.0.0 or something similar.

The main change is to force using the x86 platform, else when building on M1 (for example) it tries to pick up the ARM images.

Bref v2 will also contain ARM images, I'm not sure if that implies also building extensions on ARM specifically, but I guess it might be the case. Not sure if this is something you want to tackle outright.

**Comment by Nyholm** [comment]
Hey. 
Great work!

Hm.. okey. so we would need "arm" extensions and "x86" extension. That is fair. 

I haven't followed the changes in Bref 2.0 very closely. But I imagine that most/all extensions just needs that update because the extensions is more related to PHP than Bref. I guess if the Bref docker build images changes a lot, then it might be a bigger issue.

**Comment by shouze** [comment]
I can help.
A good thing would be to release an update of extensions for Bref 1.x supporting php 8.2 first. Then to create a 2.0 branch and adapt to bref 2.0

**Comment by mnapoli** [comment]
OK Bref v2 build images are published on Docker Hub with the version `2` (https://github.com/brefphp/aws-lambda-layers/pull/35), for example: https://hub.docker.com/r/bref/build-php-82/tags

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/720328/206715464-3a7a9b06-8f09-4ce5-bb7d-8eff9767a531.png">

**Comment by shouze** [comment]
Ok so I can imagine fork main branch to use them and adapt let's say for redis as a first commit? :angel:

**Comment by mnapoli** [comment]
👍 sounds good.

Also FYI on Bref v2 I have "standardized" (or "officialized") the extension path to `/opt/bref/extensions`. Feel free to use it, but also (alternatively) feel free not to use it if you don't want to start changing all the existing code here. Both are fine.

**Comment by shouze** [comment]
@mnapoli I've made a commit on a v2 branch on my own fork at the moment: https://github.com/shouze/extra-php-extensions/commit/d2697998309781e67e39122deda4b69d4de78984

We can discuss it.
Main drawback is that it seems we've lost `LD_LIBRARY_PATH` with bref 2.0.
For redis only: remi php-redis package enables msgpack & igbinary too, so I cannot bring redis only, it's all or none.

**Comment by shouze** [comment]
@mnapoli about `FROM --platform=linux/amd64` I'm not sure to understand : don't you want to provide multi arch bref 2 images? Or maybe it's for a later stage of the roadmap?

**Comment by shouze** [comment]
> I'd love to remove that problem entirely TBH, because I don't see an upside to dealing with these subtilities. But maybe I'm missing something.

Got it. Could be useful maybe for people that want to run Lambda on Graviton from docker images in fact. About local development I see no big deal.

**Comment by mnapoli** [comment]
On my mac I actually set `export DOCKER_DEFAULT_PLATFORM=linux/amd64` in my bash to avoid that problem altogether, but any contributor will face it I'm afraid.

**Comment by shouze** [comment]
@mnapoli as we use Makefiles, looks like a better option to set `DOCKER_DEFAULT_PLATFORM` env var for example than putting a `--platform=linux/amd64` option into the `FROM` instruction of `Dockerfiles`.


Also, we can simply use `docker buildx build` in place of `docker build`, which have a `--platform` option too. WDYT?

**Comment by mnapoli** [comment]
> @mnapoli as we use Makefiles, looks like a better option to set DOCKER_DEFAULT_PLATFORM env var for example than putting a --platform=linux/amd64 option into the FROM instruction of Dockerfiles.

Makes sense to me, not sure if you have an opinion on this @Nyholm.

TBH I don't have a strong opinion on this, I don't know much better than you on this.

**Comment by mnapoli** [comment]
@Nyholm here's what I'm thinking:

- create branch `1.x` from master
- merge branch `v2` into master
- tag `1.0.0` release (or `2.0.0`? would it be clearer for users?)

Support for ARM would come in separately (unless I can figure it out today but I don't want to block the release)

I'd love to proceed today, let me know if you think we should do something different?

**Comment by mnapoli** [comment]
I'm giving this a try today because I will be out and off for the following 3 days, let's see if that works out! 🤞
