### ISSUE TITLE
Microsoft SQL Server Layer

### ISSUE THREAD

**Issue by pfazzi** [brefphp/extra-php-extensions#47]
Add a layer that enables connections with Microsoft SQL Server

**Comment by chippyash** [comment]
Is that still a thing? Don't think I've used that in over 20 years! 🤣 Joking aside, it is relatively straightforward for you to build your own layer package and submit it for inclusion in the repo. There are instructions, I followed them to create the Ds layer quite easily.

**Comment by pfazzi** [comment]
I opened the issue just as declaration of intent. I've already implemented the gRPC layer of this repo so i can take in charge this task. Unfortunatelly I'm working on a new project that, among other stuff,  should also read some data from a legacy SQL Server so no way out for me... 😭 
I hope this layer will be as straight forward as the gRPC was 🙏

**Comment by chippyash** [comment]
@pfazzi My bad, saw this on the phone and didn't recognise you.  Have fun with the MSSQL. As I recall, it was a rip-off of the Sybase SQL server, which back in the day was a powerful and useful beast. I remember writing a financial portfolio management system totally inside the database and then using Paradox on client side to interact with it.  Happy days.

**Comment by pfazzi** [comment]
I'm too young for Paradox but my first job required me to work on a very legacy PowerBuilder project connected with Sybase 7 maybe via ODBC... nostalgic feels 😂

**Comment by Nyholm** [comment]
Excuse my ignorance. But isn't the sqlsrv layer doing this?

Ping @atbreuer11

**Comment by atbreuer11** [comment]
@Nyholm Yes! This issue predates the PR that added SQL Server support, but can be closed now.

**Comment by Nyholm** [comment]
Cool cool cool.
