### ISSUE TITLE
Libvips extension

### ISSUE THREAD

**Issue by rmundel** [brefphp/extra-php-extensions#73]
Hey guys, there's support or the possibility to support libvips? https://github.com/libvips/php-vips-ext

**Comment by mnapoli** [comment]
Hi, this might be a candidate for a separate layer in https://github.com/brefphp/extra-php-extensions

Check out [this guide](https://github.com/brefphp/extra-php-extensions/blob/master/docs/create_your_own_extension_layer.md) to contribute that extension.

**Comment by rmundel** [comment]
It's actually not that hard to do that!
I'm definitely going to build that soon!
Thanks.

**Comment by mnapoli** [comment]
Awesome!
