### ISSUE TITLE
Unknown Bref extra layer named "gd-php-74"

### ISSUE THREAD

**Issue by G3z** [brefphp/extra-php-extensions#79]
I'm receiving this error when launching `serverless`
I've added the layer this way:
`- ${bref:extra.gd-php-74}`
I see no problem when using another extension for example:
`- ${bref:extra.memcached-php-74}`

**Comment by MattGrundy** [comment]
I'm not seeing it in the layers.json so I guess the serverless plugin can't pick it up 👀

**Comment by Nyholm** [comment]
It is in layers.json.. https://github.com/brefphp/extra-php-extensions/blob/master/layers.json#L582

@G3z Did you add the plugin to serverless.yml?

**Comment by G3z** [comment]
sorry I was referring to GD (in the title) I was using memcached as an example of a working extension, i'll edit my first post

**Comment by Nyholm** [comment]
Oh, Im sorry. 

@MattGrundy is correct. GD is not released yet: https://github.com/brefphp/extra-php-extensions/compare/0.4.2...master

We are currently blocked by #80

**Comment by Nyholm** [comment]
Try with 0.5.0. That should work.
