### ISSUE TITLE
Usage with Laravel Vapor

### ISSUE THREAD

**Issue by Shnilj** [brefphp/extra-php-extensions#88]
I am currently using [Laravel Vapor](https://vapor.laravel.com/) to run Serverless PHP through AWS. By default, Vapor has an option to use Imagick based on this repository [see](https://docs.vapor.build/1.0/projects/environments.html#imagick-support). I was wondering how I can extend this functionality to add SQLSrv support to my project.

Thanks in advance!

**Comment by KennyDepecker** [comment]
I am in need of the same. help please.

**Comment by mnapoli** [comment]
Hi, since this isn't really an issue or support related to the project, let's move this discussion to https://github.com/brefphp/bref/discussions

**Comment by Shnilj** [comment]
Moved to https://github.com/brefphp/bref/discussions/823

**Comment by mnapoli** [comment]
@Shnilj please don't ping me in that discussion, anyone that can help will help.
