### ISSUE TITLE
The 0.6.0 build failed

### ISSUE THREAD

**Issue by mnapoli** [brefphp/extra-php-extensions#99]
Here is the build: https://github.com/brefphp/extra-php-extensions/runs/1442677439?check_suite_focus=true

```
Installing '/opt/bref/lib/php/extensions/no-debug-zts-20190902/yaml.so'
install ok: channel://pecl.php.net/yaml-2.1.0
configuration option "php_ini" is not set to php.ini location
You should add "extension=http://yaml.so" to php.ini
Removing intermediate container d4f47c592d7c
 ---> d4045fcd43c4
Step 8/15 : RUN cp /opt/bref/lib/php/extensions/no-debug-non-zts-*/yaml.so /tmp/yaml.so
 ---> Running in 79c801801b63
cp: cannot stat '/opt/bref/lib/php/extensions/no-debug-non-zts-*/yaml.so': No such file or directory
Makefile:19: recipe for target 'docker-images' failed
```

It seems like the `yaml` extension was compiled with zts (`/opt/bref/lib/php/extensions/no-debug-zts-20190902/yaml.so`), so the `cp` does not work.

I'm trying to understand why it was compiled with zts 🤔

**Comment by chekalsky** [comment]
Not sure if it's connected or not, but getting this error now:

/opt/bin/php: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory

**Comment by chekalsky** [comment]
@Nyholm (sorry for tagging you, but I can't test bref 1.0 without this fix apparently)

0.6.1 — still failing https://github.com/brefphp/extra-php-extensions/runs/1446390925?check_suite_focus=true

**Comment by Nyholm** [comment]
I was sure I fixed that... Hm.. 

Oh, it is because the `latest` has changed =)

**Comment by mnapoli** [comment]
@Nyholm oh right, I republished 0.5.33 as `latest` on Docker because it was messing things up for some users (1.0.0 not being released yet).

**Comment by Nyholm** [comment]
Cool cool. Then #101 should fix it

**Comment by Nyholm** [comment]
I just tagged 0.6.2
https://github.com/brefphp/extra-php-extensions/releases/tag/0.6.2

Everything should be fine now.

**Comment by mnapoli** [comment]
Thank you!
